//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Prime95.rc
//
#define IDOK2                           3
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_PRIME9TYPE                  129
#define IDD_RANGE                       130
#define IDD_NEXTRANGE                   131
#define IDD_TEST                        132
#define IDD_CPU                         133
#define IDC_CURSOR1                     133
#define IDD_TIME                        134
#define IDD_PREFERENCES                 135
#define IDC_CURSOR2                     135
#define IDD_CLEARPRIMES                 136
#define IDD_FACTOR                      137
#define IDD_RANGE_STATUS                138
#define IDD_PASSWORD                    139
#define IDD_RANGEFACTOR                 140
#define IDD_RANGEDBLCHK                 141
#define IDD_DIALOG1                     142
#define IDD_USER                        143
#define IDD_PRIMENET                    145
#define IDD_PRIORITY                    146
#define IDD_ABOUTSERVER                 147
#define IDD_VACATION                    148
#define IDD_MANUAL_COMM                 149
#define IDD_ECM                         150
#define IDD_AFFINITY                    151
#define IDD_PMINUS1                     152
#define IDI_YELLOW_ICON                 153
#define IDC_CHECK1                      1000
#define IDC_LL                          1000
#define IDC_NOISE                       1000
#define IDC_EDIT1                       1001
#define IDC_BACKUP                      1001
#define IDC_LL2                         1001
#define IDC_BIGONES                     1001
#define IDC_NEXTRANGE                   1002
#define IDC_B2                          1002
#define IDC_EDIT2                       1002
#define IDC_P                           1005
#define IDC_B1                          1006
#define IDC_DISK                        1006
#define IDC_HOURS                       1006
#define IDC_P2                          1007
#define IDC_NETWORK                     1007
#define IDC_DB                          1008
#define IDC_WORK                        1008
#define IDC_END_DATES                   1008
#define IDC_START_TIME                  1008
#define IDC_P1                          1009
#define IDC_WORK2                       1009
#define IDC_MODEM                       1009
#define IDC_END_TIME                    1009
#define IDC_CYRIX                       1010
#define IDC_P3                          1010
#define IDC_486                         1011
#define IDC_CURVE                       1011
#define IDC_PENTIUM                     1012
#define IDC_NUM_CURVES                  1012
#define IDC_PRO                         1013
#define IDC_NAME                        1013
#define IDC_EMAIL                       1014
#define IDC_K6                          1014
#define IDC_USERID                      1015
#define IDC_CELERON                     1015
#define IDC_PASSWORD                    1016
#define IDC_PII                         1016
#define IDC_FACTOR                      1017
#define IDC_COMPID                      1017
#define IDC_PIII                        1017
#define IDC_DBLCHK                      1018
#define IDC_K7                          1018
#define IDC_TEST                        1019
#define IDC_FACTOR2                     1019
#define IDC_PFACTOR                     1019
#define IDC_P4                          1019
#define IDC_DBLCHK2                     1020
#define IDC_WORK_DFLT                   1022
#define IDC_WORKGROUP                   1023
#define IDC_NETWORK_TEXT                1024
#define IDC_WORK_DFLT2                  1024
#define IDC_WORKGROUP2                  1025
#define IDC_END_DATES_TEXT              1025
#define IDC_PRIMENET                    1026
#define IDC_MODEM_TEXT                  1026
#define IDC_WORK_TEXT                   1027
#define IDC_WORK_TEXT2                  1028
#define IDC_PRIORITY                    1029
#define IDC_COMPLETION                  1029
#define IDC_LINE1                       1030
#define IDC_AFFINITY                    1030
#define IDC_LINE2                       1031
#define IDC_LINE3                       1032
#define IDC_DIALUP                      1033
#define IDC_R_ITER                      1034
#define IDC_DAYS                        1034
#define IDC_MANUAL                      1035
#define IDC_SENDEMAIL                   1035
#define IDC_NOW                         1036
#define IDC_RPC                         1036
#define IDC_HTTP                        1037
#define IDC_AFFINITY_TEXT               1038
#define IDC_PROTOCOL                    1038
#define IDC_TEAM                        1038
#define IDC_ALL_CPUS                    1039
#define IDC_NAME_TEXT                   1039
#define IDC_ID_TEXT                     1040
#define IDC_PWD_TEXT                    1041
#define IDC_PLUS1                       1042
#define IDC_MEMORY                      1043
#define IDC_DAY_MEMORY                  1044
#define IDC_NIGHT_MEMORY                1049
#define IDM_CONTINUE                    32771
#define IDM_STOP                        32772
#define IDM_ERRCHK                      32773
#define IDM_AUTO                        32774
#define IDM_RANGE                       32775
#define IDM_NEXTRANGE                   32776
#define IDM_TEST                        32777
#define IDM_TIME                        32778
#define IDM_CLEAR_PRIMES                32779
#define IDM_FACTOR                      32780
#define IDM_PREFERENCES                 32781
#define IDM_CPU                         32782
#define ID_RANGE_STATUS                 32783
#define ID_OPTIONS_SELFTEST             32784
#define IDM_PASSWORD                    32785
#define IDM_RANGEFACTOR                 32786
#define IDM_RANGESBLCHK                 32787
#define IDM_TRAY                        32788
#define IDM_HIDE                        32789
#define IDM_TORTURE                     32790
#define ID_RANGE_USERINFORMATION        32791
#define IDM_PRIMENET                    32792
#define IDM_PRIORITY                    32793
#define IDM_SERVER                      32794
#define IDM_QUIT                        32795
#define IDM_VACATION                    32796
#define IDM_MANUALCOMM                  32797
#define IDM_AFFINITY                    32798
#define IDM_ECM                         32799
#define IDM_PMINUS1                     32800
#define IDM_BROADCAST                   32802

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        149
#define _APS_NEXT_COMMAND_VALUE         32803
#define _APS_NEXT_CONTROL_VALUE         1042
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
