//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Prime95.rc
//
#define IDH_PRIMENET                    11
#define IDH_USERINFORMATION             12
#define IDH_VACATION                    13
#define IDH_RANGE_STATUS                14
#define IDH_CONTINUE                    15
#define IDH_STOP                        16
#define IDH_APP_EXIT                    17
#define IDH_PASSWORD                    18
#define IDH_TEST                        19
#define IDH_TIME                        20
#define IDH_PMINUS1                     21
#define IDH_ECM                         22
#define IDH_ERRCHK                      23
#define IDH_PRIORITY                    24
#define IDH_AFFINITY                    25
#define IDH_MANUALCOMM                  26
#define IDH_QUIT                        27
#define IDH_CPU                         28
#define IDH_PREFERENCES                 29
#define IDH_TORTURE                     31
#define IDH_TRAY                        32
#define IDH_HIDE                        33
#define IDH_SERVICE                     34
#define IDH_HELP_FINDER                 35
#define IDH_APP_ABOUT                   36
#define IDH_SERVER                      37
#define IDH_UNRESERVE                   38
#define IDH_WELCOME                     39
#define IDH_BENCHMARK                   40
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_TEST                        132
#define IDD_CPU                         133
#define IDC_CURSOR1                     133
#define IDD_TIME                        134
#define IDD_PREFERENCES                 135
#define IDC_CURSOR2                     135
#define IDD_PASSWORD                    139
#define IDD_USER                        143
#define IDD_PRIMENET                    145
#define IDD_PRIORITY                    146
#define IDD_ABOUTSERVER                 147
#define IDD_VACATION                    148
#define IDD_MANUAL_COMM                 149
#define IDD_ECM                         150
#define IDD_AFFINITY                    151
#define IDD_PMINUS1                     152
#define IDI_YELLOW_ICON                 153
#define IDD_WELCOME                     153
#define IDD_UNRESERVE                   154
#define IDR_TRAYMENU                    156
#define ID_OPEN_EXIT                    157
#define ID_TRAY_RESTORE                 158
#define ID_DUMMY_SAD                    159
#define IDC_CHECK1                      1000
#define IDC_LL                          1000
#define IDC_NOISE                       1000
#define IDC_EDIT1                       1001
#define IDC_BACKUP                      1001
#define IDC_BATTERY                     1002
#define IDC_P                           1005
#define IDC_DISK                        1006
#define IDC_HOURS                       1006
#define IDC_P2                          1007
#define IDC_NETWORK                     1007
#define IDC_WORK                        1008
#define IDC_R_ITER                      1008
#define IDC_START_TIME                  1008
#define IDC_P1                          1009
#define IDC_END_DATES                   1009
#define IDC_END_TIME                    1009
#define IDC_CYRIX                       1010
#define IDC_P3                          1010
#define IDC_MODEM                       1010
#define IDC_486                         1011
#define IDC_CURVE                       1011
#define IDC_PENTIUM                     1012
#define IDC_NUM_CURVES                  1012
#define IDC_PRO                         1013
#define IDC_NAME                        1013
#define IDC_EMAIL                       1014
#define IDC_K6                          1014
#define IDC_USERID                      1015
#define IDC_PII                         1015
#define IDC_PASSWORD                    1016
#define IDC_PIII                        1016
#define IDC_FACTOR                      1017
#define IDC_COMPID                      1017
#define IDC_CELERON                     1017
#define IDC_DBLCHK                      1018
#define IDC_K7                          1018
#define IDC_BIGONES                     1019
#define IDC_P4                          1019
#define IDC_WORK_DFLT                   1022
#define IDC_WORKGROUP                   1023
#define IDC_NETWORK_TEXT                1024
#define IDC_END_DATES_TEXT              1025
#define IDC_PRIMENET                    1026
#define IDC_MODEM_TEXT                  1026
#define IDC_WORK_TEXT                   1027
#define IDC_PRIORITY                    1029
#define IDC_COMPLETION                  1029
#define IDC_LINE1                       1030
#define IDC_AFFINITY                    1030
#define IDC_LINE2                       1031
#define IDC_LINE3                       1032
#define IDC_DIALUP                      1033
#define IDC_DAYS                        1034
#define IDC_MANUAL                      1035
#define IDC_NOW                         1036
#define IDC_SENDEMAIL                   1037
#define IDC_AFFINITY_TEXT               1038
#define IDC_TEAM                        1038
#define IDC_ALL_CPUS                    1039
#define IDC_RPC                         1040
#define IDC_HTTP                        1041
#define IDC_PLUS1                       1042
#define IDC_PROTOCOL                    1043
#define IDC_NAME_TEXT                   1044
#define IDC_DAY_MEMORY                  1044
#define IDC_ID_TEXT                     1045
#define IDC_PWD_TEXT                    1046
#define IDC_NIGHT_MEMORY                1049
#define IDC_CPU_INFO                    1056
#define IDM_CONTINUE                    32771
#define IDM_STOP                        32772
#define IDM_ERRCHK                      32773
#define IDM_TEST                        32777
#define IDM_TIME                        32778
#define IDM_PREFERENCES                 32781
#define IDM_CPU                         32782
#define ID_RANGE_STATUS                 32783
#define ID_OPTIONS_SELFTEST             32784
#define IDM_PASSWORD                    32785
#define IDM_TRAY                        32788
#define IDM_HIDE                        32789
#define IDM_TORTURE                     32790
#define ID_RANGE_USERINFORMATION        32791
#define IDM_PRIMENET                    32792
#define IDM_PRIORITY                    32793
#define IDM_SERVER                      32794
#define IDM_QUIT                        32795
#define IDM_VACATION                    32796
#define IDM_SERVICE                     32797
#define ID_MANUALCOMM                   32798
#define IDM_ECM                         32799
#define IDM_AFFINITY                    32800
#define IDM_PMINUS1                     32801
#define USR_BROADCAST                   32802
#define USR_OUTPUT_STR                  32803
#define USR_TITLE                       32804
#define IDM_UNRESERVE                   32805
#define USR_WELCOME                     32806
#define IDM_BENCHMARK                   32807
#define IDM_TRAY_OPEN                   32808
#define USR_SERVICE_STOP                32809
#define IDM_STOP_CONTINUE               32810

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        160
#define _APS_NEXT_COMMAND_VALUE         32811
#define _APS_NEXT_CONTROL_VALUE         1058
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
